---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-app-config
data:
  DB_URL: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true"
  DB_USER: "root"
---
apiVersion: v1
kind: Secret
metadata:
  name: spring-app-secret
type: Opaque
data:
  DB_PASSWORD: ""  # Mot de passe vide en base64
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Demande de stockage persistant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      # Désactiver le montage automatique du token de service account
      automountServiceAccountToken: false
      containers:
        - name: spring-boot-container
          # Utiliser un tag de version spécifique au lieu de "latest"
          image: malekmouelhi7/student-management:v1.0.0  # ⬅️ REMPLACER par votre vraie version
          ports:
            - containerPort: 8089
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
              ephemeral-storage: "1Gi"  # Demande de stockage temporaire
            limits:
              memory: "1Gi"
              cpu: "500m"               # Limite de CPU
              ephemeral-storage: "2Gi"  # Limite de stockage temporaire
          volumeMounts:
            - name: app-storage
              mountPath: /app/data       # Point de montage pour le stockage persistant
          env:
            - name: spring.datasource.url
              valueFrom:
                configMapKeyRef:
                  name: spring-app-config
                  key: DB_URL
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: spring-app-config
                  key: DB_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: spring-app-secret
                  key: DB_PASSWORD
            - name: server.port
              value: "8089"
            - name: server.servlet.context-path
              value: "/student"
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: spring-app-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring-boot-app
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30080
  type: NodePort